"""create cv tables

Revision ID: 4d0e111b105d
Revises: 
Create Date: 2026-05-09 12:59:53.091338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d0e111b105d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS cv")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('dates', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('person_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('linked_in', sa.String(), nullable=True),
    sa.Column('git_hub', sa.String(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('additional_skills', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('technology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['cv.experience.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('responsibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technical_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soft_skills_and_approach', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('semantic_summary', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['cv.project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('responsibility_technology',
    sa.Column('responsibility_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['responsibility_id'], ['cv.responsibility.id'], ),
    sa.ForeignKeyConstraint(['technology_id'], ['cv.technology.id'], ),
    sa.PrimaryKeyConstraint('responsibility_id', 'technology_id'),
    schema='cv'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsibility_technology', schema='cv')
    op.drop_table('responsibility', schema='cv')
    op.drop_table('project', schema='cv')
    op.drop_table('technology', schema='cv')
    op.drop_table('person_data', schema='cv')
    op.drop_table('experience', schema='cv')
    # ### end Alembic commands ###
